[build-system]
requires = [ "setuptools" ]

[project]
name = "example_library"
version = "1.0.0"
authors = [ { name = "Taipy" } ]
description = "A Taipy GUI extension library example."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9,<3.13"
keywords = [ "taipy" ]
license = "Apache-2.0"
classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [ "taipy-gui>=2.2" ]
