name: Build and release one taipy package

on:
  workflow_dispatch:
    inputs:
      target_package:
        description: "Package name"
        required: true
        type: choice
        options:
          - gui
          - common
          - core
          - rest
          - templates
          - taipy
      target_version:
        description: "Package version"
        required: true
      release_type:
        description: "Release type"
        required: true
        type: choice
        options:
          - dev
          - production
        default: "dev"
      sub_packages_location:
        description: "Dependencies location"
        required: true
        type: choice
        options:
          - GitHub
          - Pypi
        default: "GitHub"

env:
  NODE_OPTIONS: --max-old-space-size=4096

permissions:
  contents: write

jobs:
  setup-versions:
    runs-on: ubuntu-latest
    outputs:
        common_VERSION: ${{ steps.version-setup.outputs.common_VERSION }}
        core_VERSION: ${{ steps.version-setup.outputs.core_VERSION }}
        gui_VERSION: ${{ steps.version-setup.outputs.gui_VERSION }}
        rest_VERSION: ${{ steps.version-setup.outputs.rest_VERSION }}
        templates_VERSION: ${{ steps.version-setup.outputs.templates_VERSION }}
        taipy_VERSION: ${{ steps.version-setup.outputs.taipy_VERSION }}
        LATEST_TAIPY_VERSION: ${{ steps.version-setup.outputs.LATEST_TAIPY_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Install mandatory Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Setup Version
        id: version-setup
        run: |
          python tools/release/setup_versions.py \
          ${{ github.event.inputs.target_package }} \
          -v ${{ github.event.inputs.target_version }} \
          -t ${{ github.event.inputs.release_type }} \
          -r ${{ github.repository }} | tee -a >>$GITHUB_OUTPUT

  build-and-release-package:
    needs: setup-versions
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract commit hash
        id: extract_hash
        shell: bash
        run: echo "HASH=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Install mandatory Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update setup.requirements.txt
        run: |
          python tools/release/update_setup_requirements.py ${{ github.event.inputs.target_package }} \
            ${{ needs.setup-versions.outputs.common_VERSION }} \
            ${{ needs.setup-versions.outputs.core_VERSION }} \
            ${{ needs.setup-versions.outputs.gui_VERSION }} \
            ${{ needs.setup-versions.outputs.rest_VERSION }} \
            ${{ needs.setup-versions.outputs.templates_VERSION }} \
            -deps ${{ github.event.inputs.sub_packages_location }} \
            -r ${{ github.repository }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel pipenv mypy black isort

      - name: Install GUI dependencies
        if: ${{ github.event.inputs.target_package == 'gui' || github.event.inputs.target_package == 'taipy' }}
        run: |
          pipenv install --dev

      - name: Generate GUI pyi file
        if: github.event.inputs.target_package == 'gui'
        run: |
          pipenv run python tools/gui/generate_pyi.py

      - name: Build Taipy GUI front-end
        if: ${{ github.event.inputs.target_package == 'gui' || github.event.inputs.target_package == 'taipy' }}
        run: |
          python tools/frontend/bundle_build.py gui

      - name: Build Taipy front-end
        if: ${{ github.event.inputs.target_package == 'taipy' }}
        run: |
          python tools/frontend/bundle_build.py taipy

      - name: Build Package Structure
        run: |
          python tools/release/build_package_structure.py ${{ github.event.inputs.target_package }}

      - name: Build package
        working-directory: "build_${{ github.event.inputs.target_package }}"
        run: |
          echo step0
          pwd
          echo step1
          ls
          if [ -d dist ]; then
            echo step2
            ls dist
          fi
          python -m build
          echo step3
          ls
          if [ -d dist ]; then
            echo step4
            ls dist
          fi
          for file in ./dist/*; do mv "$file" "${file//_/-}"; done
          echo step5
          ls
          if [ -d dist ]; then
            echo step6
            ls dist
          fi
          
      - name: Create tag and release
        working-directory: "build_${{ github.event.inputs.target_package }}"
        run: |
          if [ "${{ github.event.inputs.target_package }}" == "common" ]; then
            package_version="${{ needs.setup-versions.outputs.common_VERSION }}"
          elif [ "${{ github.event.inputs.target_package }}" == "core" ]; then
            package_version="${{ needs.setup-versions.outputs.core_VERSION }}"
          elif [ "${{ github.event.inputs.target_package }}" == "gui" ]; then
            package_version="${{ needs.setup-versions.outputs.gui_VERSION }}"
          elif [ "${{ github.event.inputs.target_package }}" == "rest" ]; then
            package_version="${{ needs.setup-versions.outputs.rest_VERSION }}"
          elif [ "${{ github.event.inputs.target_package }}" == "templates" ]; then
            package_version="${{ needs.setup-versions.outputs.templates_VERSION }}"
          elif [ "${{ github.event.inputs.target_package }}" == "taipy" ]; then
            package_version="${{ needs.setup-versions.outputs.taipy_VERSION }}"
          fi
          echo "package_version: $package_version"
          package_suffix=""
          if [ "${{ github.event.inputs.target_package }}" != "taipy" ]; then
            package_suffix="-${{ github.event.inputs.target_package }}"
          fi
          echo "package_suffix: $package_suffix"
          release_name="$package_version$package_suffix"
          echo "release_name: $release_name"
          tar_path="./dist/taipy-$package_suffix$package_version.tar.gz"
          echo "tar_path: $tar_path"
          if [ "${{ github.event.inputs.release_type }}" == "dev" ]; then
            echo "before gh"
            gh release create $release_name $tar_path --target ${{ steps.extract_hash.outputs.HASH }} --prerelease --title $release_name --notes "Dev Release $release_name"
            echo "after gh"
          else
            gh release create $release_name $tar_path --target ${{ steps.extract_hash.outputs.HASH }} --title $release_name --notes "Release $release_name"
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure the latest 'taipy' production release is marked as *latest* no matter what
        run: |
          gh release edit ${{ needs.setup-versions.outputs.LATEST_TAIPY_VERSION }} --latest
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
